name: CI

on: [push, pull_request]

jobs:
  lint_and_type_check:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.11.0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        env:
          # Prisma Client 생성에는 Accelerate URL 사용 (prisma://)
          DATABASE_URL: ${{ secrets.DATABASE_URL || secrets.NEON_HTTP_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
        run: pnpm prisma generate

      - name: Run Prisma Migrations
        env:
          # 마이그레이션에는 직접 연결 URL 사용 (postgresql://)
          DATABASE_URL: ${{ secrets.DATABASE_URL_MIGRATE || secrets.NEON_HTTP_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
        run: |
          # DATABASE_URL이 postgresql://로 시작하는지 확인
          if [[ "$DATABASE_URL" == postgresql://* || "$DATABASE_URL" == postgres://* ]]; then
            echo "마이그레이션을 위한 올바른 DATABASE_URL 형식이 감지되었습니다."
            # 실제 환경에서 마이그레이션 실행
            if [[ "$DATABASE_URL" != *"dummy"* ]]; then
              pnpm prisma migrate deploy
            else
              echo "더미 URL이 감지되어 마이그레이션을 건너뜁니다."
            fi
          else
            echo "경고: DATABASE_URL이 postgresql:// 또는 postgres://로 시작하지 않습니다. 마이그레이션을 건너뜁니다."
          fi

      - name: Run linters and type checker
        env:
          # 런타임에는 Accelerate URL 사용 (prisma://)
          DATABASE_URL: ${{ secrets.DATABASE_URL || secrets.NEON_HTTP_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
          NEON_HTTP_URL: ${{ secrets.NEON_HTTP_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
        run: |
          pnpm lint
          pnpm type-check # tsc --noEmit

      - name: Build project
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || 'dummy-client-id' }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || 'dummy-client-secret' }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'dummy-nextauth-secret' }}
          # 런타임에는 Accelerate URL 사용 (prisma://)
          DATABASE_URL: ${{ secrets.DATABASE_URL || secrets.NEON_HTTP_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
          NEON_HTTP_URL: ${{ secrets.NEON_HTTP_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL || 'https://dummy-redis-url.upstash.io' }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN || 'dummy_token' }}
        run: pnpm turbo run build --cache-dir=.turbo